### ISSUE TITLE
Doesn't work / not connecting

### ISSUE THREAD

**Issue by RedSpid3r** [walterl/proton-privoxy#2]
Just seems to get stuck in a loop

```
Connecting to **** via UDP...                                                                                                                       
2021-01-18 19:46:33,298 — protonvpn-cli — DEBUG — openvpn_connect:482 — OpenVPN process started                                                     
Connection timed out after 45 Seconds                                                                                                               
2021-01-18 19:47:18,340 — protonvpn-cli — DEBUG — openvpn_connect:530 — Connection timed out after 45 Seconds                                       
Device "proton0" does not exist.                                                                                                                    
Failed to bring up VPN :(                        
```

**Comment by walterl** [comment]
Issue confirmed. It's perhaps the most annoying thing about this container 😒.

Not having found the time to fix it, I've resorted to this workaround to recreate the container after a reboot: `docker-compose down && docker-compose up -d && docker-compose logs -f`. The last one is to verify that the proxy started successfully:

```
OSError: [Errno 16] Resource busy: '/etc/resolv.conf' -> '/etc/resolv.conf.bak'
2021-01-26 18:43:52.893 7feef4c65d48 Info: Privoxy version 3.0.28
2021-01-26 18:43:52.893 7feef4c65d48 Info: Program name: privoxy
2021-01-26 18:43:52.893 7feef4c65d48 Info: Listening on port 8080 on IP address 0.0.0.0
```

(The `/etc/resolv.conf` error is expected, and something else I'd like to fix... eventually 😣.)

My working hypothesis is that the `proton0` tunnel device can't survive a container restart (because Docker), and that causes this error. The quickest/easiest solution would be to setup `protonvpn-cli` from scratch on _each_ container start (not just first one), so that the device is always created.

**Comment by walterl** [comment]
With the changes I was working on today, I got this error when I neglected to specify `HOST_NETWORK=192.168.0.0/16` (my LAN network address). It's probably needed to allow the container to figure out how to route OpenVPN traffic. Try that.
