### ISSUE TITLE
Authentication fail

### ISSUE THREAD

**Issue by Chris230291** [walterl/proton-privoxy#3]
Hello. Thanks for putting this together.
I am trying to use it with a free account but I am getting a authentication error.

Here is how I create the container...

```
docker create \
--name=ProtonProxyUS \
--restart=always \
-p 8318:8080 \
-e PVPN_USERNAME=**** \
-e PVPN_PASSWORD=****\
-e PVPN_TIER=1 \
-e PVPN_CMD_ARGS="connect us-free-01" \
walt3rl/proton-privoxy
```

...And here is the errors...

```
Connecting to US-FREE#1 via UDP...
[!] Authentication failed. 
[!] Please make sure that your Username and Password is correct.
Device "proton0" does not exist.
Failed to bring up VPN :(
```

I wonder what I am doing wrong?
I am using the login details that I use to log in to the site.

**Comment by walterl** [comment]
I'm a paying ProtonVPN user and haven't used the free service at all, so my knowledge about the differences between them are limited. That said, I'm pretty sure your problem lies here:

>  I am using the login details that I use to log in to the site.

You're looking for the _OpenVPN_ credentials associated with your account. For my account it takes the shape of random strings of 24 characters for both the username and password.
