### ISSUE TITLE
Question about DNS "con" in README

### ISSUE THREAD

**Issue by LouKordos** [walterl/proton-privoxy#4]
According to the README, DNS leaks are not prevented because a docker container cannot change its own DNS settings after being launched, right?

So I set the container DNS using `--dns 8.8.8.8`, and that worked fine. However, upon closer inspection, inside the container, `/etc/resolv.conf`, shows that the nameserver is set to the ProtonVPN subnet, and `tcpdump` confirms that 8.8.8.8 is not used at all, all DNS traffic seems to go through the VPN tunnel subnet. Does that not directly contradict what the README says, since this way, the ProtonVPN servers handle all DNS requests and forward them to the image?

**Comment by walterl** [comment]
Interesting! I distinctly remember seeing odd errors from even root shells being unable to modify `/etc/resolv.conf` (not the normal `Permission denied`), caused by it being mounted in from the host as a read-only volume (`-v /etc/resolv.conf:/etc/resolv.conf:ro`). Maybe something changed with Docker recently. I'll have to confirm, and I hope you're right! :crossed_fingers:

Or, speculating a bit further, maybe your use of `--dns` causes Docker to _not_ mount in `/etc/resolv.conf` from the host as a read-only volume, which has the _side effect_ of making it editable in the container. :thinking:

Either way, I'll play around with it a bit and see. Thanks for bringing this to my attention! :bow:

**Comment by walterl** [comment]
This is splendid! I couldn't track down what changed in Docker or when, but it seems that, while the `/etc/resolv.conf` is recreated on each container restart, it's now at least modifiable after startup (as you've described). That's good enough for what we need here, though.

As you've observed, the default behavior is now to use the DNS server set by the `protonvpn` CLI client. However, if you'd like to specify other DNS servers, you can now do so with the `DNS_SERVERS_OVERRIDE` env var I added.

**Comment by LouKordos** [comment]
Awesome, thanks for taking a look!
